[package]
name = "minidecaf"
version = "0.5.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
chrono = "0.4"
regex = "1"
peek-nth = "0.2"

[dependencies.nom]
version = "5"
features = ["regexp"]